### PR TITLE
Add explicit quest claimed state

### LINKED ISSUE #100: [Bug]: Can't see claimable rewards from Quests
### Bug Description

On the quests screen, quests that have been completed with no claimable rewards, and quests that have been completed but still have claimable rewards, appear the same even though one has a possible action and the other doesn't. 

### How to Reproduce?

1. Complete a quest with rewards
2. Open the quests screen
3. Observe the quest appearance
4. Claim all rewards for the quest
5. Revisit the quests screen
6. Observe an identical quest appearance 

### Expected Behavior

I'm not 100% on what works best to signify this. Color and border color are both good options - ftb quests of course used its little notification bubbles. I'm not sure what screams "free stuff!" the most. Maybe a nice gold border? it'll have to be much lighter than the current dark green to be colourblind friendly. 

### Version

1.0.5

### Mod Loader Version

0.20.2

### Mod Loader

_No response_

### Logs or additional context

_No response_

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

### PR DESCRIPTION
**Pull request by sisby-folk**
Closes #100

Expands quest backgrounds to include state (a kinda goldy-yellow color)
Expands quest progress widget to include state and have an outline color (matches the backgrounds)

Expanding the enum is probably mildly controversial, but given that progress isn't available on the quests screen, it was the way to go in this architecture.

https://github.com/terrarium-earth/Heracles/assets/55819817/601c3c32-ec15-4a33-b5e5-00c7034bbef4

### CODE REVIEW

**Comment by ThatGravyBoat** [comment]
Can merge conflicts be fixed please then ill review and merge

**Comment by sisby-folk** [comment]
Done up!

**Comment by sisby-folk** [comment]
Realized the rendering on the modal was wrong, so i fixed that up and added a few more builtin shapes while I was at it.

image

Pentagon isn't the best, but hey, it's there!

We'll probably remember to do another odysseus update once this is merged so that it converts these shapes.

**Comment by SubordinalBlue** [comment]
Kismet! Before reading this PR, I had submitted a shape-preserving PR for Odysseus.

**Comment by sisby-folk** [comment]
In collaboration with the whole preserving-ftb-shapes thing, we did the full set.

javaw_GYrrxX026o
javaw_ZBF96z7dHl
javaw_mDlDpE29wp


Diamond, Gear, Heart, Hexagon, Octagon, Pentagon, Rounded Square.

image

You can see here that only the rounded square can fully enclose a glass pane like the square and circle can, so pack devs will just need to be a bit discerning if they care too much about that.

Ready to review again.

**Review by ThatGravyBoat — APPROVED** [review]

**Pull request merged**
